CREATE TABLE CLASSES
(
  c_id NUMERIC(5) PRIMARY KEY,
  c_name VARCHAR(15) NOT NULL
);

CREATE TABLE STUDENTS
(
  s_id NUMERIC(5) PRIMARY KEY,
  s_name VARCHAR(20) NOT NULL,
  s_id_number CHAR(9) UNIQUE NOT NULL,
  c_id NUMERIC(5) NOT NULL,
  CONSTRAINT cs CHECK (s_id_number ~ '^[0-9]{9}$'),
  FOREIGN KEY (c_id) REFERENCES CLASSES(c_id)
);

CREATE TABLE TEACHERS
(
  t_id NUMERIC(5) PRIMARY KEY,
  t_name VARCHAR(20) NOT NULL,
  t_id_number CHAR(9) UNIQUE NOT NULL,
  c_id NUMERIC(5) UNIQUE NOT NULL,
  CONSTRAINT ct CHECK (t_id_number ~ '^[0-9]{9}$'),
  FOREIGN KEY (c_id) REFERENCES CLASSES(c_id)
);