CREATE TABLE CLASSES
(
  c_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  c_name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE STUDENTS
(
  s_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  s_name VARCHAR(20) NOT NULL,
  s_id_number CHAR(9) UNIQUE NOT NULL,
  c_id INT NOT NULL,
  CONSTRAINT cs CHECK (s_id_number ~ '^[0-9]{9}$'),
  FOREIGN KEY (c_id) REFERENCES CLASSES(c_id)
);

CREATE TABLE TEACHERS
(
  t_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  t_name VARCHAR(20) NOT NULL,
  t_id_number CHAR(9) UNIQUE NOT NULL,
  c_id INT UNIQUE NOT NULL,
  CONSTRAINT ct CHECK (t_id_number ~ '^[0-9]{9}$'),
  FOREIGN KEY (c_id) REFERENCES CLASSES(c_id)
);

CREATE TABLE LOCATIONS
(
  l_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  at_time TIMESTAMPTZ NOT NULL,
  s_id_number CHAR(9) NOT NULL,
  
  CHECK (latitude BETWEEN -90 AND 90),
  CHECK (longitude BETWEEN -180 AND 180),
  
  FOREIGN KEY (s_id_number) REFERENCES STUDENTS(s_id_number)
);

CREATE TABLE T_LOCATIONS
(
  t_l_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  at_time TIMESTAMPTZ NOT NULL,
  t_id_number CHAR(9) NOT NULL,
  
  CHECK (latitude BETWEEN -90 AND 90),
  CHECK (longitude BETWEEN -180 AND 180),
  
  FOREIGN KEY (t_id_number) REFERENCES TEACHERS(t_id_number)
);